
path: C:\Users\User\Desktop\SharkDroneCode\DATA  # dataset root dir
train: ../train/images
val: ../valid/images
test: ../test/images

nc: 4
names: ['boat', 'person', 'sealion', 'shark']

roboflow:
  workspace: d4ms
  project: marine-sharks
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/d4ms/marine-sharks/dataset/1